/* AnonymizerTokenManager.java */
/* Generated By:JavaCC: Do not edit this line. AnonymizerTokenManager.java */
import java.io.FileReader;
import java.io.FileWriter;
import java.io.Reader;
import java.io.Writer;
import java.io.IOException;

/** Token Manager. */
@SuppressWarnings ("unused")
public class AnonymizerTokenManager implements AnonymizerConstants {

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private int jjMoveStringLiteralDfa0_0()
{
   return jjMoveNfa_0(1, 0);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0x100000000000L, 0x0L
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 135;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if ((0x3ff600000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(8, 9); }
                  else if (curChar == 43)
                     jjstateSet[jjnewStateCnt++] = 36;
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(0, 7); }
                  if (curChar == 51)
                     { jjAddStates(8, 10); }
                  else if (curChar == 55)
                     { jjAddStates(11, 15); }
                  break;
               case 8:
                  if ((0x3ff600000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(8, 9); }
                  break;
               case 10:
                  if ((0x3ff200000000000L & l) != 0L)
                     { jjAddStates(16, 17); }
                  break;
               case 11:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 12;
                  break;
               case 13:
                  if (curChar == 49)
                     { jjCheckNAddStates(18, 20); }
                  break;
               case 14:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(15, 31); }
                  break;
               case 15:
                  if (curChar == 55)
                     { jjAddStates(11, 15); }
                  break;
               case 16:
                  if (curChar == 55)
                     { jjCheckNAddTwoStates(17, 18); }
                  break;
               case 17:
                  if (curChar == 32)
                     { jjCheckNAdd(18); }
                  break;
               case 18:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 19;
                  break;
               case 19:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 20;
                  break;
               case 20:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(21, 22); }
                  break;
               case 21:
                  if (curChar == 32)
                     { jjCheckNAdd(22); }
                  break;
               case 22:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 23;
                  break;
               case 23:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(24, 25); }
                  break;
               case 24:
                  if (curChar == 32)
                     { jjCheckNAdd(25); }
                  break;
               case 25:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 26;
                  break;
               case 26:
                  if ((0x3ff000000000000L & l) != 0L && kind > 3)
                     kind = 3;
                  break;
               case 27:
                  if (curChar == 54)
                     { jjCheckNAddTwoStates(17, 18); }
                  break;
               case 28:
                  if (curChar == 53)
                     { jjCheckNAddTwoStates(17, 18); }
                  break;
               case 29:
                  if (curChar == 56)
                     { jjCheckNAddTwoStates(17, 18); }
                  break;
               case 30:
                  if (curChar == 48)
                     { jjCheckNAddTwoStates(17, 18); }
                  break;
               case 31:
                  if (curChar == 51)
                     { jjAddStates(8, 10); }
                  break;
               case 32:
                  if (curChar == 51)
                     { jjCheckNAddTwoStates(17, 18); }
                  break;
               case 33:
                  if (curChar == 50)
                     { jjCheckNAddTwoStates(17, 18); }
                  break;
               case 34:
                  if (curChar == 49)
                     { jjCheckNAddTwoStates(17, 18); }
                  break;
               case 35:
                  if (curChar == 50)
                     jjstateSet[jjnewStateCnt++] = 13;
                  break;
               case 36:
                  if (curChar == 50)
                     jjstateSet[jjnewStateCnt++] = 35;
                  break;
               case 37:
                  if (curChar == 43)
                     jjstateSet[jjnewStateCnt++] = 36;
                  break;
               case 106:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(0, 7); }
                  break;
               case 107:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 108;
                  break;
               case 108:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 109;
                  break;
               case 109:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 110;
                  break;
               case 110:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 111;
                  break;
               case 111:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 112;
                  break;
               case 112:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 113;
                  break;
               case 113:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 114;
                  break;
               case 114:
               case 123:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAdd(115); }
                  break;
               case 115:
                  if ((0x3ff000000000000L & l) != 0L && kind > 4)
                     kind = 4;
                  break;
               case 116:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 117;
                  break;
               case 117:
                  if (curChar == 32)
                     jjstateSet[jjnewStateCnt++] = 118;
                  break;
               case 118:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 119;
                  break;
               case 119:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 120;
                  break;
               case 120:
                  if (curChar == 32)
                     jjstateSet[jjnewStateCnt++] = 121;
                  break;
               case 121:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 122;
                  break;
               case 122:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 123;
                  break;
               case 124:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(21, 26); }
                  break;
               case 125:
                  if (curChar == 46)
                     { jjCheckNAdd(126); }
                  break;
               case 126:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(27, 31); }
                  break;
               case 127:
                  if (curChar == 32)
                     { jjCheckNAddStates(32, 34); }
                  break;
               case 134:
                  if (curChar == 36)
                     kind = 5;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(8, 9); }
                  if ((0x7fffffe00000000L & l) != 0L)
                  {
                     if (kind > 7)
                        kind = 7;
                     { jjCheckNAdd(40); }
                  }
                  else if ((0x7fffffeL & l) != 0L)
                  {
                     if (kind > 6)
                        kind = 6;
                     { jjCheckNAdd(39); }
                  }
                  if (curChar == 77)
                     { jjCheckNAddStates(35, 40); }
                  else if (curChar == 66)
                     { jjAddStates(41, 42); }
                  else if (curChar == 78)
                     { jjAddStates(43, 44); }
                  else if (curChar == 79)
                     { jjCheckNAddTwoStates(45, 73); }
                  else if (curChar == 69)
                     { jjAddStates(45, 46); }
                  else if (curChar == 73)
                     { jjAddStates(47, 48); }
                  else if (curChar == 67)
                     { jjCheckNAddStates(49, 52); }
                  else if (curChar == 83)
                     { jjCheckNAddStates(53, 56); }
                  else if (curChar == 68)
                     { jjCheckNAddTwoStates(48, 2); }
                  else if (curChar == 85)
                     { jjCheckNAddTwoStates(45, 46); }
                  else if (curChar == 76)
                     { jjCheckNAddStates(57, 59); }
                  else if (curChar == 86)
                     jjstateSet[jjnewStateCnt++] = 6;
                  else if (curChar == 84)
                     { jjCheckNAdd(2); }
                  else if (curChar == 74)
                     { jjCheckNAdd(0); }
                  break;
               case 0:
                  if (curChar == 101 && kind > 1)
                     kind = 1;
                  break;
               case 2:
                  if (curChar == 117 && kind > 1)
                     kind = 1;
                  break;
               case 3:
                  if (curChar == 84)
                     { jjCheckNAdd(2); }
                  break;
               case 4:
                  if (curChar == 115 && kind > 1)
                     kind = 1;
                  break;
               case 5:
               case 75:
                  if (curChar == 117)
                     { jjCheckNAdd(4); }
                  break;
               case 6:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 5;
                  break;
               case 7:
                  if (curChar == 86)
                     jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 8:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(8, 9); }
                  break;
               case 9:
                  if (curChar == 64)
                     { jjCheckNAdd(10); }
                  break;
               case 10:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     { jjCheckNAddTwoStates(10, 11); }
                  break;
               case 12:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 2)
                     kind = 2;
                  { jjCheckNAddTwoStates(11, 12); }
                  break;
               case 38:
                  if ((0x7fffffeL & l) == 0L)
                     break;
                  if (kind > 6)
                     kind = 6;
                  { jjCheckNAdd(39); }
                  break;
               case 39:
                  if ((0x7fffffe00000000L & l) == 0L)
                     break;
                  if (kind > 6)
                     kind = 6;
                  { jjCheckNAdd(39); }
                  break;
               case 40:
                  if ((0x7fffffe00000000L & l) == 0L)
                     break;
                  if (kind > 7)
                     kind = 7;
                  { jjCheckNAdd(40); }
                  break;
               case 41:
                  if (curChar == 76)
                     { jjCheckNAddStates(57, 59); }
                  break;
               case 42:
                  if (curChar == 97 && kind > 1)
                     kind = 1;
                  break;
               case 43:
               case 48:
               case 51:
               case 60:
               case 68:
                  if (curChar == 101)
                     { jjCheckNAdd(4); }
                  break;
               case 44:
                  if (curChar == 85)
                     { jjCheckNAddTwoStates(45, 46); }
                  break;
               case 45:
                  if (curChar == 110 && kind > 1)
                     kind = 1;
                  break;
               case 46:
                  if (curChar == 110)
                     { jjCheckNAdd(0); }
                  break;
               case 47:
                  if (curChar == 68)
                     { jjCheckNAddTwoStates(48, 2); }
                  break;
               case 49:
                  if (curChar == 83)
                     { jjCheckNAddStates(53, 56); }
                  break;
               case 50:
               case 77:
                  if (curChar == 111)
                     { jjCheckNAdd(45); }
                  break;
               case 52:
                  if (curChar == 116 && kind > 1)
                     kind = 1;
                  break;
               case 53:
                  if (curChar == 117)
                     { jjCheckNAdd(52); }
                  break;
               case 54:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 53;
                  break;
               case 55:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 54;
                  break;
               case 56:
                  if (curChar == 67)
                     { jjCheckNAddStates(49, 52); }
                  break;
               case 57:
                  if (curChar == 116)
                     { jjCheckNAdd(0); }
                  break;
               case 58:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 57;
                  break;
               case 59:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 58;
                  break;
               case 61:
                  if (curChar == 101)
                     { jjCheckNAdd(52); }
                  break;
               case 62:
                  if (curChar == 73)
                     { jjAddStates(47, 48); }
                  break;
               case 63:
                  if (curChar == 108 && kind > 1)
                     kind = 1;
                  break;
               case 64:
                  if (curChar == 108)
                     { jjCheckNAdd(4); }
                  break;
               case 65:
                  if (curChar == 69)
                     { jjAddStates(45, 46); }
                  break;
               case 66:
                  if (curChar == 108)
                     { jjCheckNAdd(0); }
                  break;
               case 67:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 66;
                  break;
               case 69:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 68;
                  break;
               case 70:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 69;
                  break;
               case 71:
                  if (curChar == 79)
                     { jjCheckNAddTwoStates(45, 73); }
                  break;
               case 72:
                  if (curChar == 105 && kind > 1)
                     kind = 1;
                  break;
               case 73:
                  if (curChar == 117)
                     { jjCheckNAdd(72); }
                  break;
               case 74:
                  if (curChar == 78)
                     { jjAddStates(43, 44); }
                  break;
               case 76:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 75;
                  break;
               case 78:
                  if (curChar == 66)
                     { jjAddStates(41, 42); }
                  break;
               case 79:
                  if (curChar == 114 && kind > 1)
                     kind = 1;
                  break;
               case 80:
               case 94:
                  if (curChar == 117)
                     { jjCheckNAdd(79); }
                  break;
               case 81:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 80;
                  break;
               case 82:
                  if (curChar == 106)
                     jjstateSet[jjnewStateCnt++] = 81;
                  break;
               case 83:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 82;
                  break;
               case 84:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 83;
                  break;
               case 85:
                  if (curChar == 105)
                     { jjCheckNAdd(79); }
                  break;
               case 86:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 85;
                  break;
               case 87:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 86;
                  break;
               case 88:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 87;
                  break;
               case 89:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 88;
                  break;
               case 90:
                  if (curChar == 77)
                     { jjCheckNAddStates(35, 40); }
                  break;
               case 91:
                  if (curChar == 99)
                     { jjCheckNAdd(72); }
                  break;
               case 92:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 91;
                  break;
               case 93:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 92;
                  break;
               case 95:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 94;
                  break;
               case 96:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 95;
                  break;
               case 97:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 96;
                  break;
               case 98:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 97;
                  break;
               case 99:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 98;
                  break;
               case 100:
                  if (curChar == 109)
                     { jjCheckNAdd(0); }
                  break;
               case 101:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 100;
                  break;
               case 102:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 101;
                  break;
               case 103:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 102;
                  break;
               case 104:
                  if (curChar == 109 && kind > 1)
                     kind = 1;
                  break;
               case 105:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 104;
                  break;
               case 128:
                  if (curChar == 65 && kind > 5)
                     kind = 5;
                  break;
               case 129:
               case 132:
                  if (curChar == 70)
                     { jjCheckNAdd(128); }
                  break;
               case 130:
                  if (curChar == 67)
                     jjstateSet[jjnewStateCnt++] = 129;
                  break;
               case 131:
                  if (curChar == 70)
                     jjstateSet[jjnewStateCnt++] = 130;
                  break;
               case 133:
                  if (curChar == 67)
                     jjstateSet[jjnewStateCnt++] = 132;
                  break;
               case 134:
                  if (curChar == 70 && kind > 5)
                     kind = 5;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int hiByte = (curChar >> 8);
         int i1 = hiByte >> 6;
         long l1 = 1L << (hiByte & 077);
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 134:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2) && kind > 5)
                     kind = 5;
                  break;
               default : if (i1 == 0 || l1 == 0 || i2 == 0 ||  l2 == 0) break; else break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 135 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, };
protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}
static final int[] jjnextStates = {
   107, 116, 124, 125, 127, 131, 133, 134, 32, 33, 34, 16, 27, 28, 29, 30, 
   10, 11, 14, 15, 31, 124, 125, 127, 131, 133, 134, 126, 127, 131, 133, 134, 
   131, 133, 134, 93, 99, 103, 79, 0, 105, 84, 89, 76, 77, 67, 70, 63, 
   64, 0, 59, 60, 61, 50, 42, 51, 55, 0, 42, 43, 
};
private static final boolean jjCanMove_0(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 32:
         return ((jjbitVec0[i2] & l2) != 0L);
      default :
         return false;
   }
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(Exception e)
   {
      jjmatchedKind = 0;
      jjmatchedPos = -1;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedPos == 0 && jjmatchedKind > 8)
   {
      jjmatchedKind = 8;
   }
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
         matchedToken = jjFillToken();
         return matchedToken;
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

void SkipLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
void MoreLexicalActions()
{
   jjimageLen += (lengthOfMatch = jjmatchedPos + 1);
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
void TokenLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

    /** Constructor. */
    public AnonymizerTokenManager(SimpleCharStream stream){

      if (SimpleCharStream.staticFlag)
            throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");

    input_stream = stream;
  }

  /** Constructor. */
  public AnonymizerTokenManager (SimpleCharStream stream, int lexState){
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Reinitialise parser. */
  
  public void ReInit(SimpleCharStream stream)
  {


    jjmatchedPos =
    jjnewStateCnt =
    0;
    curLexState = defaultLexState;
    input_stream = stream;
    ReInitRounds();
  }

  private void ReInitRounds()
  {
    int i;
    jjround = 0x80000001;
    for (i = 135; i-- > 0;)
      jjrounds[i] = 0x80000000;
  }

  /** Reinitialise parser. */
  public void ReInit(SimpleCharStream stream, int lexState)
  
  {
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Switch to specified lex state. */
  public void SwitchTo(int lexState)
  {
    if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
    else
      curLexState = lexState;
  }


/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};

/** Lex State array. */
public static final int[] jjnewLexState = {
   -1, -1, -1, -1, -1, -1, -1, -1, -1, 
};
static final long[] jjtoToken = {
   0x1ffL, 
};
static final long[] jjtoSkip = {
   0x0L, 
};
static final long[] jjtoSpecial = {
   0x0L, 
};
static final long[] jjtoMore = {
   0x0L, 
};
    protected SimpleCharStream  input_stream;

    private final int[] jjrounds = new int[135];
    private final int[] jjstateSet = new int[2 * 135];
    private final StringBuilder jjimage = new StringBuilder();
    private StringBuilder image = jjimage;
    private int jjimageLen;
    private int lengthOfMatch;
    protected int curChar;
}
