/* Generated By:JavaCC: Do not edit this line. AnonymizerConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AnonymizerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ARTICLE = 1;
  /** RegularExpression Id. */
  int EMAIL = 2;
  /** RegularExpression Id. */
  int PHONE = 3;
  /** RegularExpression Id. */
  int DATE = 4;
  /** RegularExpression Id. */
  int AMOUNT = 5;
  /** RegularExpression Id. */
  int PERSON = 6;
  /** RegularExpression Id. */
  int WORD = 7;
  /** RegularExpression Id. */
  int OTHER = 8;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<ARTICLE>",
    "<EMAIL>",
    "<PHONE>",
    "<DATE>",
    "<AMOUNT>",
    "<PERSON>",
    "<WORD>",
    "<OTHER>",
  };

}
